### PR TITLE
Fixed BeginPopupV and BeginPopupModalV having incorrect flags type

### PR DESCRIPTION
**Pull request by the-goodies**

### CODE REVIEW

**Comment by JetSetIlly** [comment]
You're right. This was my mistake OpenPopup() and OpenPopupOnItemClickV() expects PopupFlags but BeginPopupV() and BeginPopupModalV() expects WindowFlags.

@dertseha maybe the project should have a testing branch so that this sort of issue is caught before general release?

**Comment by the-goodies** [comment]
Yeah, easy mistake to make here. I would have caught it before new version release if I would have merged your pull request earlier, since I'm using a lot of OpenPopup with WindowFlags.

**Comment by JetSetIlly** [comment]
@the-goodies Good work on adding the table API by the way. Have you done anything with the docking branch yet?

**Comment by the-goodies** [comment]
I sort of tried and was able to get docking partially working, but it's not really needed for my use case, so didn't use nor test it properly.
What's needed and would be great is multi-viewports, but it seemed rather difficult to port and time investment trying to understand and do so wasn't worth it. Maybe it would be fine if porting was sufficient, but you also have to make a lot of changes to your backend (as far as I understand), so for a time being I gave up.

**Comment by dertseha** [comment]
Thank you for catching this!

**Comment by dertseha** [comment]
As for the open question about tests:
I'd be happy if we could extend the Go-demo window in `imgui-go-examples`, which would help cross-checking API incompatibilities.
I could demand to have PRs only accepted if any extension has the corresponding update there.

I'm not so much a fan of invisible extra branches that one has to become aware of.  Granted, the examples repository is somewhat also "away" from this one here, yet it is public in its own right and also a reference implementation.

**Pull request merged**
