### PR TITLE
added Style.Color()

### PR DESCRIPTION
**Pull request by JetSetIlly**

### CODE REVIEW

**Comment by neclepsio** [comment]
I think you should name it Style.Color(), as it's idiomatic to not use
"Get" in Go.

**Comment by JetSetIlly** [comment]
> I think you should name it Style.Color(), as it's idiomatic to not use "Get" in Go.

Fair comment. Would you use Get in the naming of the C++ wrappers? So, for example, in this instance I've named the wrapper iggStyleGetColor()

**Comment by neclepsio** [comment]
I made the same mistake before, that's why I know! :)
I think that wrappers keep the Get of the function they wrap, it gets
removed only in the public api. If you look the other wrappers, you'll be
sure.

Il mar 8 set 2020, 23:37 Stephen Illingworth <notifications@github.com> ha
scritto:

**Comment by dertseha** [comment]
Hello, and thank you again for your contribution!
For reference, the idiomatic guidelines (most of them) are collected [here](https://golang.org/doc/effective_go.html), with getters having their [own section](https://golang.org/doc/effective_go.html#Getters).

**Pull request merged**
