### PR TITLE
Use imgui as a submodule.

### PR DESCRIPTION
**Pull request by fdejaeger**
You might consider this "trick", that I discovered in github.com/go-gl/glfw.
This way, you clearly separate what belongs to you from what belongs to imgui.
Since imgui API is very stable, this allows any one to easily upgrade imgui.

Having imgui as a submodule is an implementation detail.  It might be a _vendor_ like sub directory (like they do in glfw, IIRC)

### CODE REVIEW

**Comment by dertseha** [comment]
It's an interesting approach, thank you for the first try - though, there seems more work to be done, at least for the build pipeline :)
Please have a look at this as well. Most likely, GitHub actions need to be told to also checkout submodules.

**Comment by fdejaeger** [comment]
hum, maybe there is a good reason to *not* use submodule.  I fear golang modules don't resolve submodule...

**Comment by dertseha** [comment]
uhh... dumping the whole repository in a subdirectory is even less appealing here. There's so much stuff in there that's not necessary.
How about the combined variant - a subdirectory with the few necessary files manually copied in there?

**Comment by dertseha** [comment]
Closing due to inactivity.
Still, an interesting idea & concept.

**Pull request closed without merging**
