### PR TITLE
Refactor

### PR DESCRIPTION
**Pull request by neclepsio**
Move C files to separate folder, splitted imgui.go and corresponding C files in several files, updated to 1.76.

### CODE REVIEW

**Comment by dertseha** [comment]
I see you have been busy! I expect that it will again take some time until I get to it.

After a cursory glance, I found that the enums were all collected in one big file, whereas everything else was split up into separate files. Why not keep the enum/flag constants in the respective topic-files?

**Comment by dertseha** [comment]
OK, I updated some files to satisfy the linter again in parallel.
All good, I'll do a branch before that commit and then re-integrate everything.

**Comment by dertseha** [comment]
Thank you for this work! I'll now go over it and handle the details.

**Comment by neclepsio** [comment]
If I kept the enums with respective functions, Widgets.go would have been
too big. If I splitted all, there would have been too many small files.
This looked a good compromise to me.

**Comment by dertseha** [comment]
I moved the enums to the respective functions. Then they are still spread out enough and more close to where they have effect.
I'm still working on a few details, for instance I also finally took on adding a unified format for the native code. Hopefully tomorrow, Wednesday, I can merge to master.

**Pull request merged**
