### PR TITLE
Add GetItemRectMax/Min

### LINKED ISSUE #116: GetItemRectMin/Max not wrapped

### PR DESCRIPTION
**Pull request by ym1234**
Fixes #116 
I have tested this and it seems to work correctly, but I don't know cpp well.

### CODE REVIEW

**Comment by ym1234** [comment]
Where should I get the documentation from? They aren't documented here: https://github.com/ocornut/imgui/blob/master/imgui.cpp#L4651-L4661

**Comment by neclepsio** [comment]
Please remove "Get" from names, as it's not idiomatic in Go and in this lib.

**Comment by dertseha** [comment]
Thank you for your contribution!

> Where should I get the documentation from?

The documentation is typically in the header. And for these two, `imgui.h` does provide some information, which needs some slight changes to match the Go format of documentation.
After also considering the comment from neclepsio, it could read as:
```
ItemRectMin returns the upper-left bounding rectangle in screen space.
func ItemRectMin() Vec2 {
...
```

The C++ part looks fine!

**Comment by dertseha** [comment]
Cool, thanks again!

**Pull request merged**
