### PR TITLE
Add OpenGl2 renderer example using SDL2.

### PR DESCRIPTION
**Pull request by FooSoft**
Cool project, going to be using it in my game which uses SDL2 and OpenGl2. Made necessary changes to get things working with these binding and added an example.

### CODE REVIEW

**Comment by FooSoft** [comment]
You found my copy-pasta ; )

I'm still in the early phase of writing boilerplate for [my new project](https://github.com/FooSoft/lazarus), but the idea is to create an open-source Diablo 2 engine to help preserve this amazing game. I'm at the phase of implementing all the proprietary file formats, and I realized I definitely needed some UI for my tools! I use imgui all the time at my "day job" so definitely wanted it for my hobby project as well!

**Comment by thegtproject** [comment]
Alex, your diablo 2 project is something I’ve been working towards doing in Go as well for a while now. I’d love to assist if possible. Can I get a contact? My email is thegtproject@live.com<mailto:thegtproject@live.com>   I work a lot with the pixel project GitHub.com/faiface/pixel but am also doing my own thing (3D) over at GitHub.com/thegtproject/gravity  which I use this IMGUI package in 😊

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by FooSoft** [comment]
@thegtproject contact info sent!

**Comment by dertseha** [comment]
Thank you for the updates! And all the best for your project :)

**Pull request merged**
