### PR TITLE
AddImageQuad

### PR DESCRIPTION
**Pull request by VityaSchel**
Based on #182

### CODE REVIEW

**Comment by dertseha** [comment]
Thank you for your patience & contribution.
I've taken this over in a dedicated branch, apparently the linter didn't catch that there is an exported method without documentation :) I'll add it.

**Comment by dertseha** [comment]
Addendum: It took a few more passes to get it working, and I also added an `AddImageQuadV()` variant, because some parameters are with defaults. Have fun!

**Comment by VityaSchel** [comment]
АХУЕТЬ ПРОСТО АХУЕТЬ МОИМ ГЛАЗАМ НЕ ВЕРЮ САМ МОЙ ПИАР ЗАМЕРДЖИЛИ??? ЭТО ЗНАЧИТ ТИПА ЧТО 8 МЕСЯЦЕВ ОЖИДАНИЯ ЗАКОНЧЕНЫ И Я МОГУ НАКОНЕЦ ТО РАБОТАТЬ 🤯🤯🤯🤯🤯🤯🤯🤯😵😵😵😵😵😵😵😵😵😵🥵🥵🥵🥵🥵🥵🥵🥵☠☠💀💀💀💀💀💀💀💀😫😫

**Comment by VityaSchel** [comment]
> Thank you for your patience & contribution.
> I've taken this over in a dedicated branch, apparently the linter didn't catch that there is an exported method without documentation :) I'll add it.

Thank you!

**Pull request merged**
