### PR TITLE
features + fix

### PR DESCRIPTION
**Pull request by melaurent**
I propose those changes which include:
- AddText(pos Vec2, col PackedColor, text string) method to add text to the draw list
- A fix of CalcTextSize which didn't take into account the null character at the end of the string
- DisplayFrameBufferScale method to get the scale of frame buffer to display size for retina displays
- SetDisplayFrameBufferScale method to set the scale of frame buffer to display size for retina displays
- SetItemAllowOverlap method to support SetItemAllowOverlap
- PushItemFlag and PopItemFlag method and the corresponding flag constants

### CODE REVIEW

**Comment by melaurent** [comment]
fixed the linting but it's not updating

**Comment by dertseha** [comment]
Thank you for your contribution and your patience. I still need to find some time to look at this, hopefully the upcoming week.

**Comment by dertseha** [comment]
Thank you again, also for your patience - there are a few typos I'll fix in a dedicated branch. It's been sitting long enough now.

**Comment by melaurent** [comment]
Thanks and sorry for the typos !

**Pull request merged**
